name: Keep Render App Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # This cron expression schedules the workflow to run every 5 minutes

jobs:
  keep-awake:
    runs-on: ubuntu-latest

    steps:
      - name: Send GET request to keep app awake
        run: curl -X GET https://video-streaming-application.onrender.com/
